name: color_and_fun
description: Kids Colouring Game - Canvas, templates, brush, pencil, eraser & more.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  gal: ^2.3.2
  google_fonts: ^6.1.0
  video_player: ^2.8.2
  audioplayers: ^6.1.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  # Font configuration - uncomment after adding font files to fonts/ directory
  # fonts:
  #   - family: VAGRoundedNextShine
  #     fonts:
  #       - asset: fonts/VAGRoundedNextShine-Regular.ttf
  #       - asset: fonts/VAGRoundedNextShine-Bold.ttf
  #         weight: 700

  assets:
    - assets/opening-video.mp4
    - assets/images/
    - assets/images/animals/
    - assets/images/dinosaurs/
    - assets/images/princess/
    - assets/images/transport/
    - assets/images/sea/
    - assets/images/robots/
    - assets/images/aliens/
    - assets/images/christmas/
    - assets/images/nature/
    - assets/images/food/
    - assets/images/fantasy/
    - assets/images/categories/
    # - assets/images/sports/
    # - assets/images/places/
    - assets/images/background/
    - assets/icons/
    - images/
    - images/Background/
    - images/Templets/
    - images/Templets/aliens/
    - images/Templets/animals/
    - images/Templets/christmas/
    - images/Templets/dinosaurs/
    - images/Templets/fantasy/
    - images/Templets/food/
    - images/Templets/nature/
    - images/Templets/princess/
    - images/Templets/robots/
    - images/Templets/sea-creatures/
    - images/Templets/transport/
    - assets/sounds/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app-icon.png"
